# Tên của workflow
name: Deploy to EC2

# Chạy khi push vào nhánh main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Lấy code về Runner
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Tạo file .env ngay trên Runner từ GitHub Secrets
      # (Để lát nữa copy sang EC2 cùng với source code luôn)
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_PRODUCTION }}" > .env

      # Bước 3: Copy toàn bộ code (bao gồm cả file .env vừa tạo) sang EC2
      - name: Sync repository files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./" # Copy tất cả (bao gồm .env)
          target: "~/ChatAppAPI"

      # Bước 4: SSH vào để chạy Docker Compose
      - name: Run deployment commands on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Đi vào thư mục
            cd ~/ChatAppAPI
            
            # Kiểm tra xem file .env đã qua chưa (Optional - để debug)
            if [ -f .env ]; then
              echo "✅ Found .env file."
            else
              echo "❌ Error: .env file is missing!"
              exit 1
            fi
            
            # Dừng container cũ
            echo "🛑 Stopping old containers..."
            docker-compose down
            
            # Chạy lại với cấu hình mới
            echo "🚀 Building Userapi..."
            docker-compose up -d --build --force-recreate userapi
            docker-compose up --force-recreate userapi

            echo "🚀 Building Chatapi ..."
            docker-compose up -d --build --force-recreate chatapi
            docker-compose up --force-recreate -d chatapi

            echo "🚀 Building Notificationapi..."
            docker-compose up -d --build --force-recreate notificationapi
            docker-compose up --force-recreate -d notificationapi

            echo "🚀 Building NGHINX..."
            docker-compose up -d --build --force-recreate nginx
            docker-compose up --force-recreate -d nginx
            
            # Dọn dẹp image thừa
            docker image prune -f
            
            echo "✅ Deployment successful!"